name: Pipeline Full Stack .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: CI
  construir_y_publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar y Compilar
        run: |
          dotnet restore src/Backend/**/*.csproj
          dotnet build src/Backend/**/*.csproj --configuration Release --no-restore

      - name: Ejecutar Pruebas
        run: dotnet test tests/**/*.csproj --no-build --verbosity normal

      - name: Publicar Aplicacion
        run: dotnet publish src/Backend/**/*.csproj -c Release -o ./publish_output

      - name: Subir Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-app-compilada
          path: ./publish_output

  # JOB 2: CD (Entrega Continua / Deploy)
  desplegar_en_produccion:
    runs-on: ubuntu-latest
    needs: construir_y_publicar
    steps:
      - name: Descargar el Artifact
        uses: actions/download-artifact@v4
        with:
          name: mi-app-compilada

      - name: Simular Deploy
        run: echo "Desplegando en el servidor..."