name: Mi practica de pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ETAPA 1: CI 
  construir-proyecto:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version  : '8.0.x'

      - name: Restaurar paquetes
        run: dotnet restore src/Backend/MiApi/MiApi.csproj

      - name: Compilar Backend
        run: dotnet build src/Backend/MiApi/MiApi.csproj --configuration Release

      - name: Ejecutar Pruebas
        run: dotnet test tests/UnitTests/MiApi.Tests.csproj
# ETAPA 2: CD (Entrega Continua / Deploy)
  desplegar-en-produccion:
    runs-on: ubuntu-latest
    needs: construir-y-publicar # Solo corre si la etapa anterior fue exitosa
    steps:
      - name: Descargar el Artifact guardado
        uses: actions/download-artifact@v4
        with:
          name: mi-app-compilada

      - name: Simular Deploy en Azure (Ejemplo)
        # Nota: En un caso real, aquí usarías 'azure/webapps-deploy@v2' con tus credenciales
        run: echo "Desplegando archivos compilados en el servidor de producción en Italia..."

